# Generated by Django 3.2.12 on 2022-04-21 10:19

import django.core.validators
from django.db import migrations, models
import lukimgather.auth_validators
import lukimgather.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user/images', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=lukimgather.fields.LowerCharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Length can be between 5 to 20. Letters, digits and ./-/_ only.', max_length=40, unique=True, validators=[lukimgather.auth_validators.CustomASCIIUsernameValidator, django.core.validators.MinLengthValidator(limit_value=5)], verbose_name='Username'),
        ),
    ]
